# Generated by Django 2.1.1 on 2018-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaI', models.TimeField()),
                ('fechaF', models.TimeField()),
                ('precio', models.CharField(max_length=50)),
                ('demandante', models.CharField(max_length=50)),
                ('oferente', models.CharField(max_length=50)),
            ],
        ),
    ]
