# Generated by Django 2.1.1 on 2018-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio' = models.CharField(max_length=50)),
                ('fecha_inicio' = models.CharField(max_length=40)),
                ('fecha_caduca'  = models.CharField(max_length=30)),
                ('carro' = models.CharField(max_length=30)),
                ('parqueadero' = models.CharField(max_length=30)),
                ('oferente', models.CharField(max_length=30)),
            ],
        ),
    ]
